In [17]:
!sudo apt install graphviz

Reading package lists... Done
Building dependency tree       
Reading state information... Done
graphviz is already the newest version (2.40.1-2).
0 upgraded, 0 newly installed, 0 to remove and 39 not upgraded.


In [18]:
!pip install -U pip
!pip install -U MNN

In [20]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [21]:
%cd /content/drive/MyDrive/Intern/21-DeepSort/Ultra-Light-Fast-Generic-Face-Detector-1MB/MNN/python

/content/drive/MyDrive/Intern/21-DeepSort/Ultra-Light-Fast-Generic-Face-Detector-1MB/MNN/python


In [5]:
!python tracking_ultraface_py_mnn.py  --model_path ../model/version-RFB/RFB-320.mnn \
--source /content/drive/MyDrive/Intern/21-DeepSort/Ultra-Light-Fast-Generic-Face-Detector-1MB/MNN/python/videos/test_video.mp4 \
--save-vid \
--config_deepsort /content/drive/MyDrive/Intern/21-DeepSort/Ultra-Light-Fast-Generic-Face-Detector-1MB/MNN/python/deep_sort/configs/deep_sort.yaml \


deep_sort/deep/reid/torchreid/metrics/rank.py:12: UserWarning: Cython evaluation (very fast so highly recommended) is unavailable, now use python evaluation.
  'Cython evaluation (very fast so highly recommended) is '

Available ReID models for automatic download
['resnet50_market1501', 'resnet50_dukemtmcreid', 'resnet50_msmt17', 'resnet50_fc512_market1501', 'resnet50_fc512_dukemtmcreid', 'resnet50_fc512_msmt17', 'mlfn_market1501', 'mlfn_dukemtmcreid', 'mlfn_msmt17', 'hacnn_market1501', 'hacnn_dukemtmcreid', 'hacnn_msmt17', 'mobilenetv2_x1_0_market1501', 'mobilenetv2_x1_0_dukemtmcreid', 'mobilenetv2_x1_0_msmt17', 'mobilenetv2_x1_4_market1501', 'mobilenetv2_x1_4_dukemtmcreid', 'mobilenetv2_x1_4_msmt17', 'osnet_x1_0_market1501', 'osnet_x1_0_dukemtmcreid', 'osnet_x1_0_msmt17', 'osnet_x0_75_market1501', 'osnet_x0_75_dukemtmcreid', 'osnet_x0_75_msmt17', 'osnet_x0_5_market1501', 'osnet_x0_5_dukemtmcreid', 'osnet_x0_5_msmt17', 'osnet_x0_25_market1501', 'osnet_x0_25_dukemtmcreid', 'osnet_x0_25

In [22]:
import yaml
yaml.__version__

'6.0'

In [8]:
!pip install -U PyYAML

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 596.3/596.3 KB 10.3 MB/s eta 0:00:00
  Attempting uninstall: PyYAML
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [3]:
!python tracking_ultraface_py_mnn.py  --model_path ../model/version-RFB/RFB-320.mnn \
--source /content/drive/MyDrive/Intern/21-DeepSort/Ultra-Light-Fast-Generic-Face-Detector-1MB/MNN/python/videos/test_video.mp4 \
--save-vid \
--config_deepsort /content/drive/MyDrive/Intern/21-DeepSort/Ultra-Light-Fast-Generic-Face-Detector-1MB/MNN/python/deep_sort/configs/deep_sort.yaml \

deep_sort/deep/reid/torchreid/metrics/rank.py:12: UserWarning: Cython evaluation (very fast so highly recommended) is unavailable, now use python evaluation.
  'Cython evaluation (very fast so highly recommended) is '

Available ReID models for automatic download
['resnet50_market1501', 'resnet50_dukemtmcreid', 'resnet50_msmt17', 'resnet50_fc512_market1501', 'resnet50_fc512_dukemtmcreid', 'resnet50_fc512_msmt17', 'mlfn_market1501', 'mlfn_dukemtmcreid', 'mlfn_msmt17', 'hacnn_market1501', 'hacnn_dukemtmcreid', 'hacnn_msmt17', 'mobilenetv2_x1_0_market1501', 'mobilenetv2_x1_0_dukemtmcreid', 'mobilenetv2_x1_0_msmt17', 'mobilenetv2_x1_4_market1501', 'mobilenetv2_x1_4_dukemtmcreid', 'mobilenetv2_x1_4_msmt17', 'osnet_x1_0_market1501', 'osnet_x1_0_dukemtmcreid', 'osnet_x1_0_msmt17', 'osnet_x0_75_market1501', 'osnet_x0_75_dukemtmcreid', 'osnet_x0_75_msmt17', 'osnet_x0_5_market1501', 'osnet_x0_5_dukemtmcreid', 'osnet_x0_5_msmt17', 'osnet_x0_25_market1501', 'osnet_x0_25_dukemtmcreid', 'osnet_x0_25

In [4]:
!python tracking_ultraface_py_mnn.py  --model_path ../model/version-RFB/RFB-320.mnn \
--source /content/drive/MyDrive/Intern/21-DeepSort/Ultra-Light-Fast-Generic-Face-Detector-1MB/MNN/python/videos/test_video.mp4 \
--save-vid \
--config_deepsort /content/drive/MyDrive/Intern/21-DeepSort/Ultra-Light-Fast-Generic-Face-Detector-1MB/MNN/python/deep_sort/configs/deep_sort.yaml \

deep_sort/deep/reid/torchreid/metrics/rank.py:12: UserWarning: Cython evaluation (very fast so highly recommended) is unavailable, now use python evaluation.
  'Cython evaluation (very fast so highly recommended) is '
Traceback (most recent call last):
  File "tracking_ultraface_py_mnn.py", line 33, in <module>
^C


In [5]:
!pip install -U Cython

In [7]:
!python tracking_ultraface_py_mnn.py  --model_path ../model/version-RFB/RFB-320.mnn \
--source /content/drive/MyDrive/Intern/21-DeepSort/Ultra-Light-Fast-Generic-Face-Detector-1MB/MNN/python/videos/test_video.mp4 \
--save-vid \
--config_deepsort /content/drive/MyDrive/Intern/21-DeepSort/Ultra-Light-Fast-Generic-Face-Detector-1MB/MNN/python/deep_sort/configs/deep_sort.yaml \

Streaming output truncated to the last 5000 lines.
 [444 110  56  71]
 [830 111  53  61]
 [325 104  66  90]
 [273 106  30  38]
 [181 123  56  70]
 [918  79  28  32]
 [139  78  18  24]]
confs=[0.99964321 0.9969067  0.99224806 0.99076766 0.98941225 0.98126137
 0.97274446 0.74515027 0.69067365 0.63177127 0.54216415]
clss=[1 1 1 1 1 1 1 1 1 1 1]
inference time: 0.0112 s
[0.99902117 0.9963659  0.99345422 0.99116957 0.98971307 0.98451275
 0.98100466 0.74305445 0.64791232 0.60211706 0.59743965]
xywhs=[[630 113  63  70]
 [971 134  54  60]
 [549 125  48  61]
 [715 120  48  59]
 [443 111  55  71]
 [830 111  54  61]
 [327 105  65  88]
 [273 107  31  40]
 [138  77  17  23]
 [918  79  28  32]
 [177 121  48  58]]
confs=[0.99902117 0.9963659  0.99345422 0.99116957 0.98971307 0.98451275
 0.98100466 0.74305445 0.64791232 0.60211706 0.59743965]
clss=[1 1 1 1 1 1 1 1 1 1 1]
inference time: 0.0113 s
[0.99924916 0.99565768 0.99348986 0.98873621 0.98591053 0.98492223
 0.96861535 0.70446211 0.67522836 0.6208

In [15]:
!python tracking_ultraface_py_mnn.py  --model_path ../model/version-RFB/RFB-320.mnn \
--source /content/drive/MyDrive/Intern/21-DeepSort/Ultra-Light-Fast-Generic-Face-Detector-1MB/MNN/python/videos/short_test_video.mp4 \
--save-vid \
--save-txt \
--config_deepsort /content/drive/MyDrive/Intern/21-DeepSort/Ultra-Light-Fast-Generic-Face-Detector-1MB/MNN/python/deep_sort/configs/deep_sort.yaml \

Streaming output truncated to the last 5000 lines.
cls = 1
bbox_left = 3, type(bbox_left) = <class 'numpy.int64'>
txt_path = runs/track/face_detect_osnet_ibn_x1_0_MSMT17/tracks/short_test_video
j=7, id = 52
cls = 1
bbox_left = 152, type(bbox_left) = <class 'numpy.int64'>
txt_path = runs/track/face_detect_osnet_ibn_x1_0_MSMT17/tracks/short_test_video
j=8, id = 53
cls = 1
bbox_left = 312, type(bbox_left) = <class 'numpy.int64'>
txt_path = runs/track/face_detect_osnet_ibn_x1_0_MSMT17/tracks/short_test_video
j=9, id = 54
cls = 1
bbox_left = 544, type(bbox_left) = <class 'numpy.int64'>
txt_path = runs/track/face_detect_osnet_ibn_x1_0_MSMT17/tracks/short_test_video
j=10, id = 55
cls = 1
bbox_left = 856, type(bbox_left) = <class 'numpy.int64'>
txt_path = runs/track/face_detect_osnet_ibn_x1_0_MSMT17/tracks/short_test_video
j=11, id = 56
cls = 1
bbox_left = 976, type(bbox_left) = <class 'numpy.int64'>
txt_path = runs/track/face_detect_osnet_ibn_x1_0_MSMT17/tracks/short_test_video
inference time

In [13]:
!rm -rf /content/drive/MyDrive/Intern/21-DeepSort/Ultra-Light-Fast-Generic-Face-Detector-1MB/MNN/python/runs/track

In [24]:
!python tracking_ultraface_py_mnn.py  --model_path ../model/version-RFB/RFB-320.mnn \
--source /content/drive/MyDrive/Intern/21-DeepSort/Ultra-Light-Fast-Generic-Face-Detector-1MB/MNN/python/videos/short_test_video.mp4 \
--save-vid \
--save-txt \
--config_deepsort /content/drive/MyDrive/Intern/21-DeepSort/Ultra-Light-Fast-Generic-Face-Detector-1MB/MNN/python/deep_sort/configs/deep_sort.yaml \

Streaming output truncated to the last 5000 lines.
cls = 1
bbox_left = 3, type(bbox_left) = <class 'numpy.int64'>
txt_path = runs/track/face_detect_osnet_ibn_x1_0_MSMT172/tracks/short_test_video
j=7, id = 52
cls = 1
bbox_left = 152, type(bbox_left) = <class 'numpy.int64'>
txt_path = runs/track/face_detect_osnet_ibn_x1_0_MSMT172/tracks/short_test_video
j=8, id = 53
cls = 1
bbox_left = 312, type(bbox_left) = <class 'numpy.int64'>
txt_path = runs/track/face_detect_osnet_ibn_x1_0_MSMT172/tracks/short_test_video
j=9, id = 54
cls = 1
bbox_left = 544, type(bbox_left) = <class 'numpy.int64'>
txt_path = runs/track/face_detect_osnet_ibn_x1_0_MSMT172/tracks/short_test_video
j=10, id = 55
cls = 1
bbox_left = 856, type(bbox_left) = <class 'numpy.int64'>
txt_path = runs/track/face_detect_osnet_ibn_x1_0_MSMT172/tracks/short_test_video
j=11, id = 56
cls = 1
bbox_left = 976, type(bbox_left) = <class 'numpy.int64'>
txt_path = runs/track/face_detect_osnet_ibn_x1_0_MSMT172/tracks/short_test_video
inferenc

In [26]:
!python tracking_ultraface_py_mnn.py  --model_path ../model/version-RFB/RFB-320.mnn \
--source /content/drive/MyDrive/Intern/21-DeepSort/Ultra-Light-Fast-Generic-Face-Detector-1MB/MNN/python/videos/short_test_video.mp4 \
--save-vid \
--save-txt \
--config_deepsort /content/drive/MyDrive/Intern/21-DeepSort/Ultra-Light-Fast-Generic-Face-Detector-1MB/MNN/python/deep_sort/configs/deep_sort.yaml \

deep_sort/deep/reid/torchreid/metrics/rank.py:12: UserWarning: Cython evaluation (very fast so highly recommended) is unavailable, now use python evaluation.
  'Cython evaluation (very fast so highly recommended) is '

Available ReID models for automatic download
['resnet50_market1501', 'resnet50_dukemtmcreid', 'resnet50_msmt17', 'resnet50_fc512_market1501', 'resnet50_fc512_dukemtmcreid', 'resnet50_fc512_msmt17', 'mlfn_market1501', 'mlfn_dukemtmcreid', 'mlfn_msmt17', 'hacnn_market1501', 'hacnn_dukemtmcreid', 'hacnn_msmt17', 'mobilenetv2_x1_0_market1501', 'mobilenetv2_x1_0_dukemtmcreid', 'mobilenetv2_x1_0_msmt17', 'mobilenetv2_x1_4_market1501', 'mobilenetv2_x1_4_dukemtmcreid', 'mobilenetv2_x1_4_msmt17', 'osnet_x1_0_market1501', 'osnet_x1_0_dukemtmcreid', 'osnet_x1_0_msmt17', 'osnet_x0_75_market1501', 'osnet_x0_75_dukemtmcreid', 'osnet_x0_75_msmt17', 'osnet_x0_5_market1501', 'osnet_x0_5_dukemtmcreid', 'osnet_x0_5_msmt17', 'osnet_x0_25_market1501', 'osnet_x0_25_dukemtmcreid', 'osnet_x0_25

In [27]:
!python tracking_ultraface_py_mnn.py  --model_path ../model/version-RFB/RFB-320.mnn \
--source /content/drive/MyDrive/Intern/21-DeepSort/Ultra-Light-Fast-Generic-Face-Detector-1MB/MNN/python/videos/short_video_test_02.mp4 \
--save-vid \
--save-txt \
--config_deepsort /content/drive/MyDrive/Intern/21-DeepSort/Ultra-Light-Fast-Generic-Face-Detector-1MB/MNN/python/deep_sort/configs/deep_sort.yaml \

deep_sort/deep/reid/torchreid/metrics/rank.py:12: UserWarning: Cython evaluation (very fast so highly recommended) is unavailable, now use python evaluation.
  'Cython evaluation (very fast so highly recommended) is '

Available ReID models for automatic download
['resnet50_market1501', 'resnet50_dukemtmcreid', 'resnet50_msmt17', 'resnet50_fc512_market1501', 'resnet50_fc512_dukemtmcreid', 'resnet50_fc512_msmt17', 'mlfn_market1501', 'mlfn_dukemtmcreid', 'mlfn_msmt17', 'hacnn_market1501', 'hacnn_dukemtmcreid', 'hacnn_msmt17', 'mobilenetv2_x1_0_market1501', 'mobilenetv2_x1_0_dukemtmcreid', 'mobilenetv2_x1_0_msmt17', 'mobilenetv2_x1_4_market1501', 'mobilenetv2_x1_4_dukemtmcreid', 'mobilenetv2_x1_4_msmt17', 'osnet_x1_0_market1501', 'osnet_x1_0_dukemtmcreid', 'osnet_x1_0_msmt17', 'osnet_x0_75_market1501', 'osnet_x0_75_dukemtmcreid', 'osnet_x0_75_msmt17', 'osnet_x0_5_market1501', 'osnet_x0_5_dukemtmcreid', 'osnet_x0_5_msmt17', 'osnet_x0_25_market1501', 'osnet_x0_25_dukemtmcreid', 'osnet_x0_25

In [31]:
!python tracking_ultraface_py_mnn.py  --model_path ../model/version-RFB/RFB-320.mnn \
--source /content/drive/MyDrive/Intern/21-DeepSort/Ultra-Light-Fast-Generic-Face-Detector-1MB/MNN/python/videos/short_video_test_02.mp4 \
--save-vid \
--save-txt \
--config_deepsort /content/drive/MyDrive/Intern/21-DeepSort/Ultra-Light-Fast-Generic-Face-Detector-1MB/MNN/python/deep_sort/configs/deep_sort.yaml \

deep_sort/deep/reid/torchreid/metrics/rank.py:12: UserWarning: Cython evaluation (very fast so highly recommended) is unavailable, now use python evaluation.
  'Cython evaluation (very fast so highly recommended) is '

Available ReID models for automatic download
['resnet50_market1501', 'resnet50_dukemtmcreid', 'resnet50_msmt17', 'resnet50_fc512_market1501', 'resnet50_fc512_dukemtmcreid', 'resnet50_fc512_msmt17', 'mlfn_market1501', 'mlfn_dukemtmcreid', 'mlfn_msmt17', 'hacnn_market1501', 'hacnn_dukemtmcreid', 'hacnn_msmt17', 'mobilenetv2_x1_0_market1501', 'mobilenetv2_x1_0_dukemtmcreid', 'mobilenetv2_x1_0_msmt17', 'mobilenetv2_x1_4_market1501', 'mobilenetv2_x1_4_dukemtmcreid', 'mobilenetv2_x1_4_msmt17', 'osnet_x1_0_market1501', 'osnet_x1_0_dukemtmcreid', 'osnet_x1_0_msmt17', 'osnet_x0_75_market1501', 'osnet_x0_75_dukemtmcreid', 'osnet_x0_75_msmt17', 'osnet_x0_5_market1501', 'osnet_x0_5_dukemtmcreid', 'osnet_x0_5_msmt17', 'osnet_x0_25_market1501', 'osnet_x0_25_dukemtmcreid', 'osnet_x0_25

In [32]:
!python tracking_ultraface_py_mnn.py  --model_path ../model/version-RFB/RFB-320.mnn \
--source /content/drive/MyDrive/Intern/21-DeepSort/Ultra-Light-Fast-Generic-Face-Detector-1MB/MNN/python/videos/short_video_test_02.mp4 \
--save-vid \
--save-txt \
--config_deepsort /content/drive/MyDrive/Intern/21-DeepSort/Ultra-Light-Fast-Generic-Face-Detector-1MB/MNN/python/deep_sort/configs/deep_sort.yaml \

deep_sort/deep/reid/torchreid/metrics/rank.py:12: UserWarning: Cython evaluation (very fast so highly recommended) is unavailable, now use python evaluation.
  'Cython evaluation (very fast so highly recommended) is '

Available ReID models for automatic download
['resnet50_market1501', 'resnet50_dukemtmcreid', 'resnet50_msmt17', 'resnet50_fc512_market1501', 'resnet50_fc512_dukemtmcreid', 'resnet50_fc512_msmt17', 'mlfn_market1501', 'mlfn_dukemtmcreid', 'mlfn_msmt17', 'hacnn_market1501', 'hacnn_dukemtmcreid', 'hacnn_msmt17', 'mobilenetv2_x1_0_market1501', 'mobilenetv2_x1_0_dukemtmcreid', 'mobilenetv2_x1_0_msmt17', 'mobilenetv2_x1_4_market1501', 'mobilenetv2_x1_4_dukemtmcreid', 'mobilenetv2_x1_4_msmt17', 'osnet_x1_0_market1501', 'osnet_x1_0_dukemtmcreid', 'osnet_x1_0_msmt17', 'osnet_x0_75_market1501', 'osnet_x0_75_dukemtmcreid', 'osnet_x0_75_msmt17', 'osnet_x0_5_market1501', 'osnet_x0_5_dukemtmcreid', 'osnet_x0_5_msmt17', 'osnet_x0_25_market1501', 'osnet_x0_25_dukemtmcreid', 'osnet_x0_25

In [33]:
!rm -rf /content/drive/MyDrive/Intern/21-DeepSort/Ultra-Light-Fast-Generic-Face-Detector-1MB/MNN/python/runs/track